/* eslint-disable global-require */

export default images = {
  splash_logo : require('../assets/images/splash_logo.png'),
  Axle_NoTires : require('../assets/images/Axle_NoTires.png'),
  Back_Arrow : require('../assets/images/Back_Arrow.png'),
  Upload : require('../assets/images/Upload.png'),
  Lock : require('../assets/images/Lock.png'),
  Phone_Menu : require('../assets/images/Phone_Menu.png'),
  Arrow_White_Left : require('../assets/images/Arrow_White_Left.png'),
  Back_Arrow : require('../assets/images/Back_Arrow.png'),
  Check_Small : require('../assets/images/Check_Small.png'),
  Close : require('../assets/images/Close.png'),
  Search_Glass : require('../assets/images/Search_Glass.png'),
  Hamburger : require('../assets/images/Hamburger.png'),
  google_direction: require('../assets/images/Google_Directions.png'),
  wheeler_view: require('../assets/images/Wheeler_view.png'),
  arrow_up: require('../assets/images/Arrow_Up.png'),
  dotted_line: require('../assets/images/Dotted_Line.png'),
  Back_Arrow : require('../assets/images/Back_Arrow.png'),
  pin: require('../assets/images/Pin.png'),
  map_location: require('../assets/images/Map_Location.png'),
  Phone_Green_Contact: require('../assets/images/Phone_Green_Contact.png'),
  Email_Green_Contact: require('../assets/images/Email_Green_Contact.png'),
  Pin_Green_Contact: require('../assets/images/Pin_Green_Contact.png'),
  Circle_Check : require('../assets/images/Circle_Check.png'),
  Plus : require('../assets/images/Plus.png'),
  Arrow_Right : require('../assets/images/Arrow_Right.png'),
  Pin_Map : require('../assets/images/Pin_Map.png'),
  Pin_Menu : require('../assets/images/Pin_Menu.png'),
  Pin_Tab : require('../assets/images/Pin_Tab.png'),
  Bill_Green : require('../assets/images/Bill_Green.png'),
  Bill_White : require('../assets/images/Bill_White.png'),
  Pic_Empty : require('../assets/images/Pic_Empty.png'),
  Close_White : require('../assets/images/Close_White.png'),
  Dollars_Menu: require('../assets/images/Dollars_Menu.png'),
  Gift_Menu: require('../assets/images/Gift_Menu.png'),
  Pin_Menu_White: require('../assets/images/Pin_Menu_White.png'),
  Dollars_Menu_White: require('../assets/images/Dollars_Menu_White.png'),
  Gift_Tab: require('../assets/images/Gift_Tab.png'),
  Phone_Tab: require('../assets/images/Phone_Tab.png'),
  Clock : require('../assets/images/Clock.png'),
  truck_Icon : require('../assets/images/truck_Icon.png'),
  Check_Confirmation_Large : require('../assets/images/Check_Confirmation_Large.png'),
  Safety_Pin: require('../assets/images/Safety_Pin.png'),
  Camera: require('../assets/images/Camera.png'),
  Doc: require('../assets/images/Doc.png'),
  calendar_icon: require('../assets/images/calendar_icon.png'),
  Arrow_Down: require('../assets/images/Arrow_Down.png'),
  Truck: require('../assets/images/truck.png')
};
