
/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

/* USER */
export const GETUSER_SUCCESS = 'GETUSER_SUCCESS';
export const GETUSER_FAIL = 'GETUSER_FAIL';
export const SET_USER_TYPE = 'SET_USER_TYPE';

/* SHIPMENTS */
export const GET_ALL_AVAILABLE_SHIPMENTS_REQUEST = 'GET_ALL_AVAILABLE_SHIPMENTS_REQUEST';
export const GET_ALL_AVAILABLE_SHIPMENTS_SUCCESS = 'GET_ALL_AVAILABLE_SHIPMENTS_SUCCESS';
export const GET_ALL_AVAILABLE_SHIPMENTS_FAIL = 'GET_ALL_AVAILABLE_SHIPMENTS_FAIL';
export const SELECT_SHIPMENT = 'SELECT_SHIPMENT';
export const ACCEPT_SHIPMENT_REQUEST = 'ACCEPT_SHIPMENT_REQUEST';
export const ACCEPT_SHIPMENT_SUCCESS = 'ACCEPT_SHIPMENT_SUCCESS';
export const ACCEPT_SHIPMENT_FAIL = 'ACCEPT_SHIPMENT_FAIL';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

/* RESET PASSWORD */
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';